global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: legend-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8000
